p8105_hw1_mm6410
================
Mahdi Maktabi - mm6410
2024-09-19

This document is P8105 Homework 1.

I loaded necessary packages (e.g. `tidyverse`).

## Problem 1

``` r
data("penguins", package = "palmerpenguins")

penguins =
  janitor::clean_names(penguins)
```

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
mean(penguins[["flipper_length_mm"]], na.rm = TRUE)
```

    ## [1] 200.9152

Looking at the data, there are:

- 344 rows and 8 columns (variables)
- Variable include: Species, Island, Bill Length (mm), Bill Depth (mm),
  Flipper Length (mm), Body Mass (g), Sex, and Year.
- The mean of flipper_length_mm = 200.9152

``` r
ggplot(
  penguins, 
  aes(x = bill_length_mm, y = flipper_length_mm, color = species)) +  
  geom_point()
```

![](p8105_hw1_mm6410_files/figure-gfm/unnamed-chunk-3-1.png)<!-- -->

``` r
ggsave("HW1_scatterplot.pdf")
```

------------------------------------------------------------------------

## Problem 2

``` r
example_df = tibble(
  norm_samp = rnorm(10),
  norm_samp_pos = norm_samp > 0,
  char_vec = letters[1:10],
  factor_vec = factor(rep(c("Level1", "Level2", "Level3"), length.out = 10))
)

mean(pull(example_df, norm_samp))
```

    ## [1] -0.1702799

``` r
mean(pull(example_df, norm_samp_pos))
```

    ## [1] 0.4

``` r
mean(pull(example_df, char_vec))
```

    ## Warning in mean.default(pull(example_df, char_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(example_df, factor_vec))
```

    ## Warning in mean.default(pull(example_df, factor_vec)): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

- I was able to take the mean of norm_samp and norm_samp_pos. I was not
  able to take the mean of char_vec and factor_vec.

``` r
mutate(example_df,
  char_vec = as.numeric(as.factor(char_vec)),
  factor_vec = as.numeric(factor_vec)
  )
```

- When I convert char_vec into a numeric variable, it ends up swapping
  all of the letters to numbers. For example, a becomes 1, b becomes 2,
  and so on.

- Similarly, when I covert factor_vec into numeric variable, it removes
  all the characters and simply keeps the numbers.

- This makes sense because in both cases, this is the only way to covert
  them into a numeric value. So if you try to take the mean of the
  character or factor, it will just give an error because it does not
  detect a numerical value.
